name: 'Create Release'
description: 'Greet someone'
inputs:
  version-type:
    required: true
    default: 'patch'
  github-token:
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        set -x
        if [[ ! -x "$(which hub)" ]]; then
          echo "Missing hub cli, install it here:"
          echo "https://github.com/github/hub"
          exit 1
        fi

        if [[ ! -x "$(which git)" ]]; then
          echo "Missing git command"
          exit 1
        fi

        # Last 5 recent tags
        tags=$(git for-each-ref refs/tags --sort=-taggerdate --format='%(refname)' --count=5)

        # Find a semantic version
        current_tag="0.0.1"
        for tag in tags; do
          if [[ $tag =~ "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}" ]]; then
            current_tag=$tag
            echo "Found the latest semantic tag $tag"
            break
          fi
        done

        tag_array=$(echo $current_tag | tr '.' ' ')

        if [[ tag_array[@] != 3 ]]; then
          echo "Invalud tag $current_tag"
          exit 1
        fi

        type=${{ inputs.version-type }}
        major=$tag_array[0]
        minor=$tag_array[1]
        patch=$tag_array[2]


        case $type in
          "major")
            major=$(( $major + 1 ))
            ;;
          "minor")
            minor=$(( $minor + 1 ))
            ;;
          "patch")
            patch=$(( $patch + 1 ))
            ;;
          *)
        esac

        echo "$major.$minor.$patch"

      shell: bash
