name: Sauce connect
description: Sauce connect
author: Andy Hsieh
inputs:
  sauce-username:
    required: true
  sauce-access-key:
    required: true
  tunnel-identifier:
    default: github-action-tunnel
  version:
    default: 4.6.2
  debug:
    default: false
runs:
  using: composite
  steps:
    - run: |

        version="${{ inputs.version }}"
        username="${{ inputs.sauce-username }}"
        accessKey="${{ inputs.sauce-access-key }}"
        tunnel="${{ inputs.tunnel-identifier }}"
        temp="$(mktemp)"


        if [[ "${{ inputs.debug }}" == "true" ]]; then
          set -x
        fi

        curl --location --silent "https://saucelabs.com/downloads/sc-$version-linux.tar.gz" | tar -xz
        sc-$version-linux/bin/sc --tunnel-identifier=$tunnel -u $username -k $accessKey -l $temp &
        while ! grep "Sauce Connect is up, you may start your tests." $temp ; do
          echo "Sauce Connect is booting..."
          sleep 1
        done

        rm -f "$temp"

      shell: bash
