name: Platform Data Graph Subgraph Integration
description: Perform different action to support integrating subgraphs into the platform data graph
author: OneGraph team
branding:
  color: pink
  icon: box

runs:
  using: "composite"
  steps:
    - name: Install Rover
      shell: bash
      run: |
        docker run \
          -e APOLLO_KEY \
          -e GITHUB_TOKEN \
          -e SUBGRAPH_NAME \
          -e SUBGRAPH_SCHEMA_PATH \
          -e SUBGRAPH_DEFAULT_BRANCH=${{ github.event.repository.default_branch }} \
          -e SUBGRAPH_REPOSITORY=${GITHUB_REPOSITORY} \
          -e SUBGRAPH_GIT_SHA=${GITHUB_SHA} \
          -e SUBGRAPH_GIT_REF=${GITHUB_REF} \
          gcr.io/docker-images-180022/apps/platform-data-graph-sdk:latest \
          subgraph-integration
