# Trigger a scan on every Monday at 00:00:00 UTC
name: scan-docker

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: 0 0 * * 1

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: zendesk/checkout@master
      - name: build images
        run: |
          pushd samson-create-release
          docker build -t samson:latest .
          popd

          pushd slack-post-msg
          docker build -t slack:latest .
          popd
      - name: Run Snyk to check samson-create-release image for vulnerabilities
        uses: zendesk/snyk_actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: samson:latest
      - name: Run Snyk to check slack-post-msg image for vulnerabilities
        uses: zendesk/snyk_actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: slack:latest
