name: scan-docker

on:
  push

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: zendesk/checkout@master
      - name: build images
        run: |
          pushd samson-create-release
          docker build -t samson:latest .
          popd

          pushd slack-post-msg
          docker build -t slack:latest .
          popd
      - name: Run Snyk to check Docker image for vulnerabilities
        uses: zendesk/snyk_actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: samson:latest
      - name: Run Snyk to check Docker image for vulnerabilities
        uses: zendesk/snyk_actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: slack:latest
